AddTextEntry("WEAPON_MAC", "MAC-10")
AddTextEntry("WEAPON_G18C", "Glock 18c")
AddTextEntry("WEAPON_G17", "Glock 17")
AddTextEntry("WEAPON_GARDONE", "H&L Gardone")
AddTextEntry("WEAPON_DRACO", "Mini Drac")
AddTextEntry("WEAPON_M870", "Remington M870")
AddTextEntry("WEAPON_TEC9", "TEC-9")
AddTextEntry("WEAPON_MP5", "MP5")
AddTextEntry("WEAPON_FNX", "FNX .45")
AddTextEntry("WEAPON_G30", "Glock 30")
AddTextEntry("WEAPON_BARRETT", "Barrett 50")
AddTextEntry("WEAPON_P226", "P226R")
AddTextEntry("WEAPON_SIG516", "SIG516")
AddTextEntry("WEAPON_PAINTBALL", "Paintball Gun")
AddTextEntry("WEAPON_NSR", "NSR")